apiVersion: v1
appVersion: "1.0"
description: A Helm chart to deploy resources which install Citrix ADC CPX in Istio Service Mesh as sidecar in application pod
name: citrix-cpx-istio-sidecar-injector
version: 1.0.0
icon: https://github.com/citrix/citrix-istio-adaptor/blob/master/docs/media/Citrix_icon.png 
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-istio-adaptor
maintainers:
- name: Dhiraj Gedam
  email: dhiraj.gedam@citrix.com
- name: Subash Dangol
  email: subash.dangol@citrix.com 
